exec-once = XDG_MENU_PREFIX=plasma- kbuildsycoca6
exec-once = hyprpaper
exec-once = kitty +kitten panel --edge=background --output-name=DP-1 drift --scene starfield
# exec-once = nm-applet
exec-once = wl-paste --watch cliphist store
exec-once = otd-daemon
exec-once = otd loadsettings ~/dotfiles/tablet/laptop_screen
exec-once = nm-applet --indicator
