input {
    kb_layout = us
    repeat_delay = 250
    repeat_rate = 71

    follow_mouse = 1

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = true
    }
}

device {
	name = at-translated-set-2-keyboard
	kb_layout = dk
	kb_variant = nodeadkeys
	repeat_delay = 250
	repeat_rate = 70
	kb_options = compose:caps
}

# gesture = 3, horizontal, workspace

device {
    name = wacom-co.-ltd.-------cintiq-pro-13-touch-touchscreen
    enabled = false
}

# gestures {
#     workspace_swipe = true
# }

# Example per-device config
# See https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs for more
