windowrule {
	name = dev-window1
	match:title = window_dev
	size = 1000 720
	move = 1500 0
	workspace = 1
}

windowrule {
	name = dev-window2
	match:title = window_dev2
	size = 720 720
	move = 2160 360
	workspace = 2
}

# Ignore maximize requests from apps. You'll probably like this.
# windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
# windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

misc {
  enable_anr_dialog = false
  anr_missed_pings = 10
}
